FROM python:3.8

ADD . .

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

CMD [ "celery", "-A", "worker.celery", "worker", "--loglevel=debug", "--concurrency=10", "-P", "solo", "-n", "%h"]